### ISSUE TITLE
Commit .cabal file

### ISSUE THREAD

**Issue by hasufell** [litxio/streamly-cassava#1]
Please commit the .cabal file. Hpack should only be a development tool, every haskell repository should have a cabal file, otherwise this repository cannot be used with [source-repository-package](https://cabal.readthedocs.io/en/latest/nix-local-build.html#specifying-packages-from-remote-version-control-locations) of cabal.

**Comment by RichardWarfield** [comment]
Done.  Interestingly `stack new` seems to put the cabal file in .gitignore.
